// lib/constants.ts

// 1. チャンネルリスト
export const NIJISANJI_CHANNELS = [
    { id: "UCX7YkU9nEeaoZbkVLVajcMg", name: "にじさんじ" },
    { id: "UC_T8F2CvqZOwa2kme0WwRhg", name: "にじさんじ公式切り抜き" },
    { id: "UCwi4P78SVunSYAGrvC9aKcw", name: "ROF-MAO / ろふまお" },
    { id: "UCz6vnIbgiqFT9xUcD6Bp65Q", name: "ChroNoiR" },
    { id: "UCNRh9kkByBTYLo0IJupnAug", name: "VOLTACTION" },
    { id: "UCh-GyPNxvjTsza0ptjnkh1w", name: "VΔLZ" },
    { id: "UCxWcO9CLti4uouUIS5IIF-Q", name: "Nornis" },
    { id: "UChqQiUSyI-Q1j3k57_mAJHA", name: "Rain Drops" },
    { id: "UCiphSlsDcJJQ7mDqR9Q3SdA", name: "3SKM" },
    { id: "UCYjdP5F0ds2D6deMo5rpoyw", name: "いずれ菖蒲か杜若" },
    { id: "UCZzBZtqCowlyG4ZXr6R_pIw", name: "Speciale" },
    { id: "UCT5-iIJ3np5QwBkp_OiBTYQ", name: "今宵、××と夢を見る。" },
    { id: "UCGEMpMpll4otCdnnxQ9paFg", name: "sakuyui ch / さくゆい" },
    { id: "UCh98mDig5OrbsF-JUXbD5LA", name: "Sepiast" },
    { id: "UCVj0qG8hr8On0r5uYqpGE4w", name: "Idios" },
    { id: "UCwNNw9kUM-Bo0n2ktXOPB7Q", name: "Oriens" },
    { id: "UCHRCp0CSacVnTVS2Z4x9xYg", name: "七次元生徒会" },
    { id: "UC0nC50_Q8qvLbtFe6FtXpuw", name: "すぷれあ" },

    { id: "UCD-miitqNY3nyukJ4Fnf4_A", name: "月ノ美兎" },
    { id: "UCYKP16oMX9KKPbrNgo_Kgag", name: "える" },
    { id: "UCsg-YqdqQ-KFF0LNk23BY4A", name: "樋口楓" },
    { id: "UC6oDys1BGgBsIC3WhG1BovQ", name: "静凛" },
    { id: "UCeK9HFcRZoTrvqcUCtccMoQ", name: "渋谷ハジメ" },
    { id: "UCvmppcdYf4HOv-tFQhHHJMA", name: "モイラ" },
    { id: "UCmUjjW5zF1MMOhYUwwwQv9Q", name: "宇志海いちご" },
    { id: "UC_GCs6GARLxEHxy1w40d6VQ", name: "家長むぎ" },
    { id: "UC48jH1ul-6HOrcSSfoR02fQ", name: "夕陽リリ" },
    { id: "UCt0clH12Xk1-Ej5PXKGfdPA", name: "物述有栖" },
    { id: "UCBiqkFJljoxAj10SoP2w2Cg", name: "文野環" },
    { id: "UCXU7YYxy_iQd3ulXyO-zC2w", name: "伏見ガク" },
    { id: "UCUzJ90o1EjqUbk2pBAy0_aw", name: "ギルザレンⅢ世" },
    { id: "UCv1fFr156jc65EMiLbaLImw", name: "剣持刀也" },
    { id: "UCtpB6Bvhs1Um93ziEDACQ8g", name: "森中花咲" },
    { id: "UCspv01oxUFf_MTSipURRhkA", name: "叶" },
    { id: "UCBi8YaVyZpiKWN3_Z0dCTfQ", name: "赤羽葉子" },
    { id: "UCoztvTULBYd3WmStqYeoHcA", name: "笹木咲" },
    { id: "UC0g1AE0DOjBYnLhkgoRWN1w", name: "本間ひまわり" },
    { id: "UC9EjSJ8pvxtvPdxLOElv73w", name: "魔界ノりりむ" },
    { id: "UCSFCh5NL4qXrAy9u-u2lX3g", name: "葛葉" },
    { id: "UC_4tXjqecqox5Uc05ncxpxg", name: "椎名唯華" },
    { id: "UC53UDnhAAYwvNO7j_2Ju1cQ", name: "ドーラ" },
    { id: "UCRV9d6YCYIMUszK-83TwxVA", name: "轟京子" },
    { id: "UC1zFJrfEKvCixhsjNSb1toQ", name: "シスター・クレア" },
    { id: "UCsFn_ueskBkMCEyzCEqAOvg", name: "花畑チャイカ" },
    { id: "UCKMYISTJAQ8xTplUPHiABlA", name: "社築" },
    { id: "UCryOPk2GZ1meIDt53tL30Tw", name: "鈴木勝" },
    { id: "UCt5-0i4AVHXaWJrL8Wql3mw", name: "緑仙" },
    { id: "UC3lNFeJiTq6L3UWoz4g1e-A", name: "卯月コウ" },
    { id: "UCWz0CSYCxf4MhRKPDm220AQ", name: "神田笑一" },
    { id: "UCiSRx1a2k-0tOg-fs6gAolQ", name: "飛鳥ひな" },
    { id: "UCtAvQ5U0aXyKwm2i4GqFgJg", name: "春崎エアル" },
    { id: "UCRWOdwLRsenx2jLaiCAIU4A", name: "雨森小夜" },
    { id: "UCV5ZZlLjk5MKGg3L0n0vbzw", name: "鷹宮リオン" },
    { id: "UCJubINhCcFXlsBwnHp0wl_g", name: "舞元啓介" },
    { id: "UCPvGypSgfDkVe7JG2KygK7A", name: "竜胆尊" },
    { id: "UCjlmCrq4TP1I4xguOtJ-31w", name: "でびでび・でびる" },
    { id: "UCfQVs_KuXeNAlGa3fb8rlnQ", name: "桜凛月" },
    { id: "UCo7TRj3cS-f_1D9ZDmuTsjw", name: "町田ちま" },
    { id: "UChUJbHiTVeGrSkTdBzVfNCQ", name: "ジョー・力一" },
    { id: "UCbc8fwhdUNlqi-J99ISYu4A", name: "ベルモンド・バンデラス" },
    { id: "UCvzVB-EYuHFXHZrObB8a_Og", name: "矢車りね" },
    { id: "UCTIE7LM5X15NVugV7Krp9Hw", name: "夢追翔" },
    { id: "UCmeyo5pRj_6PXG-CsGUuWWg", name: "黒井しば" },
    { id: "UCCVwhI5trmaSxfcze_Ovzfw", name: "夢月ロア" },
    { id: "UCufQu4q65z63IgE4cfKs1BQ", name: "語部紡" },
    { id: "UCXRlIK3Cw_TJIQC5kSJJQMg", name: "戌亥とこ" },
    { id: "UCHVXbQzkl3rDfsXWo8xi2qw", name: "アンジュ・カトリーナ" },
    { id: "UCZ1xuCK1kNmn5RzPYIZop3w", name: "リゼ・ヘルエスタ" },
    { id: "UCNW1Ex0r6HsWRD4LCtPwvoQ", name: "三枝明那" },
    { id: "UC0WwEfE-jOM2rzjpdfhTzZA", name: "愛園愛美" },
    { id: "UC_a1ZYZ8ZTXpjg9xUY9sj8w", name: "鈴原るる" },
    { id: "UCHX7YpFG8rVwhsHCx34xt7w", name: "雪城眞尋" },
    { id: "UCIytNcoz4pWzXfLda0DoULQ", name: "エクス・アルビオ" },
    { id: "UCtnO2N4kPTXmyvedjGWdx3Q", name: "レヴィ・エリファ" },
    { id: "UCfipDDn7wY-C-SoUChgxCQQ", name: "葉山舞鈴" },
    { id: "UCUc8GZfFxtmk7ZwSO7ccQ0g", name: "ニュイ・ソシエール" },
    { id: "UCGYAYLDE7TZiiC8U6teciDQ", name: "葉加瀬冬雪" },
    { id: "UCmovZ2th3Sqpd00F5RdeigQ", name: "加賀美ハヤト" },
    { id: "UCL34fAoFim9oHLbVzMKFavQ", name: "夜見れな" },
    { id: "UCdpUojq0KWZCN9bxXnZwz5w", name: "アルス・アルマル" },
    { id: "UCkIimWZ9gBJRamKF0rmPU8w", name: "天宮こころ" },
    { id: "UCpNH2Zk2gw3JBjWAKSyZcQQ", name: "エリー・コニファー" },
    { id: "UCIG9rDtgR45VCZmYnd-4DUw", name: "ラトナ・プティ" },
    { id: "UC2OacIzd2UxGHRGhdHl1Rhw", name: "早瀬走" },
    { id: "UC8C1LLhBhf_E2IBPLSDJXlQ", name: "健屋花那" },
    { id: "UCHBhnG2G-qN0JrrWmMO2FTA", name: "シェリン・バーガンディ" },
    { id: "UCwrjITPwG4q71HzihV2C7Nw", name: "フミ" },
    { id: "UC9V3Y3_uzU5e-usObb6IE1w", name: "星川サラ" },
    { id: "UCllKI7VjyANuS1RXatizfLQ", name: "山神カルタ" },
    { id: "UCl1oLKcAq93p-pwKfDGhiYQ", name: "えま★おうがすと" },
    { id: "UCb6ObE-XGCctO3WrjRZC-cw", name: "ルイス・キャミー" },
    { id: "UCerkculBD7YLc_vOGrF7tKg", name: "魔使マオ" },
    { id: "UC6wvdADTJ88OfIbJYIpAaDA", name: "不破湊" },
    { id: "UCuvk5PilcvDECU7dDZhQiEw", name: "白雪巴" },
    { id: "UCS-XXTgVkotkbkDnGEprXpg", name: "ましろ爻" },
    { id: "UCRcLAVTbmx2-iNcXSsupdNA", name: "来栖夏芽" },
    { id: "UCuep1JCrMvSxOGgGhBfJuYw", name: "フレン・E・ルスタリオ" },
    { id: "UCmZ1Rbthn-6Jm_qOGjYsh5A", name: "イブラヒム" },
    { id: "UCXW4MqCQn-jCaxlX-nn-BYg", name: "長尾景" },
    { id: "UCGw7lrT-rVZCWHfdG9Frcgg", name: "弦月藤士郎" },
    { id: "UCo2N7C-Z91waaR6lF3LL_jw", name: "甲斐田晴" },
    { id: "UC_82HBGtvwN1hcGeOGHzUBQ", name: "空星きらめ" },
    { id: "UCL_O_HXgLJx3Auteer0n0pA", name: "周央サンゴ" },
    { id: "UCebT4Aq-3XWb5je1S1FvR_A", name: "東堂コハク" },
    { id: "UCRqBKoKuX30ruKAq05pCeRQ", name: "北小路ヒスイ" },
    { id: "UCkngxfPbmGyGl_RIq4FA3MQ", name: "西園チグサ" },
    { id: "UCgmFrRcyH7d1zR9sIVQhFow", name: "ローレン・イロアス" },
    { id: "UC-6rZgmxZSIbq786j3RD5ow", name: "レオス・ヴィンセント" },
    { id: "UCqjTqdVlvIipZXIKeCkHKUA", name: "オリバー・エバンス" },
    { id: "UCRm6lqtdxs_Qo6HeL-SRQ-w", name: "レイン・パターソン" },
    { id: "UCAQDFeCTVdx90GtwohwjHzQ", name: "天ヶ瀬むゆ" },
    { id: "UCe22Bcwd_GCpTjLxn83zl7A", name: "先斗寧" },
    { id: "UCtHY-tP0dyykhTRMmnfPs_g", name: "海妹四葉" },
    { id: "UCgIfLpQvelloDi8I0Ycbwpg", name: "壱百満天原サロメ" },
    { id: "UCC7rRD6P7RQcx0hKv9RQP4w", name: "風楽奏斗" },
    { id: "UC4l9gz3q65lTBFfFtW5LLeA", name: "渡会雲雀" },
    { id: "UCcDDxnoQcezyTUzHg5uHaKg", name: "四季凪アキラ" },
    { id: "UC5dJFf4m-mEcoyJRfhBljoA", name: "セラフ・ダズルガーデン" },
    { id: "UCUP8TmlO7NNra88AMqGU_vQ", name: "小清水透" },
    { id: "UCWRPqA0ehhWV4Hnp27PJCkQ", name: "獅子堂あかり" },
    { id: "UClrQ7xhRBxS_v_-WuudGKmA", name: "鏑木ろこ" },
    { id: "UCu-rV2gPtJ-CsGxe71z_BrQ", name: "五十嵐梨花" },
    { id: "UCtLfA_qUqCJtjXJM2ZR_keg", name: "石神のぞみ" },
    { id: "UCivwPlOp0ojnMPZj5pNOPPA", name: "ソフィア・ヴァレンタイン" },
    { id: "UCiA-trSZfB0i92V_-dyDqBw", name: "倉持めると" },
    { id: "UCy8P3o5XlMpJGQY4WugzdNA", name: "佐伯イッテツ" },
    { id: "UC1vawzfbCnRpHT9SJ5pHlHw", name: "赤城ウェン" },
    { id: "UCambvP8yxNDot4FzQc9cgiw", name: "宇佐美リト" },
    { id: "UCqXxS-9x9Ha_UiH6hG4kh5Q", name: "緋八マナ" },
    { id: "UCgZ0pH7j6c9z-pkOG3PYw1Q", name: "星導ショウ" },
    { id: "UChdY64fJb14Nfnbs8EGdQig", name: "叢雲カゲツ" },
    { id: "UC6WFKwYptsxVue56Lx218vg", name: "小柳ロウ" },
    { id: "UCz89MGFBrAqwJ5xMr5weSuA", name: "伊波ライ" },
    { id: "UCnbJ8LTbHrsRgqkxwJXCU8w", name: "立伝都々" },
    { id: "UC7_MFM9b8hp5kuTSpa8WyOQ", name: "栞葉るり" },
    { id: "UCFtyinR2ZdvKK_Xgy07qXUg", name: "ミラン・ケストレル" }, { id: "", name: "" },
    { id: "UCcx3crxPFi006DUhb_YU-tw", name: "北見遊征" },
    { id: "UC8SJPcLpIM3x8RdBJFfiluw", name: "魁星" },
    { id: "UCyXBNgCulibV9pRm3ZKpmoQ", name: "榊ネス" },
    { id: "UCzsCWYuvPUky3-DKzphYbEw", name: "司賀りこ" },
    { id: "UCkhViRjLUKgIcVpar9JiNrw", name: "珠乃井ナナ" },
    { id: "UCiJ_Um3KbfF19NzkDYLzZVQ", name: "綺沙良" },
    { id: "UCyJOgJhgfoVRpFjsBCUmuvg", name: "梢桃音" },
    { id: "UCzNXpqpdvlibmNc1JpM1o4g", name: "ルンルン" },
    { id: "UCtC3B1n4XMiJmrDtu1Ni5qw", name: "七瀬すず菜" },
    { id: "UC0xry7czPasj1wPxR8L0MZg", name: "早乙女ベリー" },
    { id: "UCw-kTlPnZYSHhlGMFJ17Znw", name: "雲母たまこ" },
    { id: "UCkQ8i_cz0prqdo9jj__L93Q", name: "酒寄颯馬" },
    { id: "UCpjypWF_wNRs9_TrjjWngpQ", name: "渚トラウト" },
    { id: "UCcyiT8QT7fo7LrxXe1oxOoA", name: "一橋綾人" },
    { id: "UCiBBDZ-ndtBgE4xKbswlgXQ", name: "五木左京" },
    { id: "UCrRdBPzK4sj-MMvYOhHRvHg", name: "十河ののは" },
    { id: "UCBjcx01rZwPDuUPzWLTsZVA", name: "夜牛詩乃" },
    { id: "UCIq2HwA2iBOso7ar4VuU-TA", name: "蝸堂みかる" },
    { id: "UCaAu0DXNSPXCZPg6iHVwRVw", name: "猫屋敷美紅" },
    { id: "UCcYrL_GQe8X8K2ARhw_Syww", name: "皇れお" },
    { id: "UCo96eJdTpPOrxHFztYajbtg", name: "篠宮ゆの" },
    { id: "UCHVSA2OScyef9W7OwPGgJ9w", name: "城瀬いすみ" },
    { id: "UCcswLVd6KGBf5mIdzeO83bA", name: "花籠つばさ" },
    { id: "UCam_xf14FPFsRshFTj4wkHw", name: "白砂あやね" },
    { id: "UCGLS7BOgNa6c03r7VYacblw", name: "水面まどか" },

    { id: "UCIeSUTOTkF9Hs7q3SGcO-Ow", name: "Elira Pendora" },
    { id: "UCu-J8uIXuLZh16gG-cT1naw", name: "Finana Ryugu" },
    { id: "UCgA2jKRkqpY_8eysPUs8sjw", name: "Petra Gurin" },
    { id: "UCR6qhsLpn62WVxCBK1dkLow", name: "Enna Alouette" },
    { id: "UC47rNmkDcNgbOcM-2BwzJTQ", name: "Millie Parfait" },
    { id: "UCckdfYDGrjojJM28n5SHYrA", name: "Vox Akuma" },
    { id: "UC7Gb7Uawe20QyFibhLl1lzA", name: "Luca Kaneshiro" },
    { id: "UCG0rzBZV_QMP4MtWg6IjhEA", name: "Shu Yamino" },
    { id: "UCQ1zGxHrfEmmW4CPpBx9-qw", name: "Alban Knox" },
    { id: "UCuuAb_72QzK0M1USPMEl1yw", name: "Sonny Brisko" },
    { id: "UChJ5FTsHOu72_5OVx0rvsvQ", name: "Uki Violeta" },
    { id: "UCwaS8_S7kMiKA3izlTWHbQg", name: "Maria Marionette" },
    { id: "UCN68LoM3khS4gdBMiWJO8WA", name: "Aia Amare" },
    { id: "UCKu59gTZ_rdEmerdx5rV4Yg", name: "Ren Zotto" },
    { id: "UCFgXWZOUZA2oYHNr6qDmsTQ", name: "Scarle Yonaguni" },
    { id: "UCy91xBlY_Brh3bnHxKtjrrg", name: "Doppio Dropscythe" },
    { id: "UChKXd7oqD18qiIYBoRIHTlw", name: "Meloco Kyoran" },
    { id: "UCO8WcDsF5znr-qsXlzZNpqg", name: "Ver Vermillion" },
    { id: "UCKpKC3M5fkcEvtOr06dmYlA", name: "Yu Q. Wilson" },
    { id: "UCpYf6C9QsP_BRf97vLuXlIA", name: "Vantacrow Bringer" },
    { id: "UCK9l6rTwU3hiSZijIMq51Gw", name: "Vezalius Bandage" },
    { id: "UCdh-YF2gTzqDNu0VU9lwPPw", name: "Claude Clawmark" },
    { id: "UCIzZDiilcPv0wim_MbuizFA", name: "Ryoma Barrenwort" },
    { id: "UCQYwIUCLqFoin7lHKmePjJw", name: "Klara Charmwood" },
    { id: "UClMYGvekJOb51eBOCK-d4Dw", name: "Zeal Ginjoka" },
    { id: "UCr40BzcLiGruKe7M5gXR9zQ", name: "Freodore" },
    { id: "UCCugV2RWXqJMjVVQl_Yh4TQ", name: "Seible" },
    { id: "UCEFOogmvTTcCaO8Qe0I8-tg", name: "Kaelix Debonair" },

    { id: "UCUtKkGKef8BYMs3h-3zQm9A", name: "ミン スゥーハ" },
    { id: "UCpRXCTyNNa-MnjhK6gisnRw", name: "ガオン" },
    { id: "UC5ek2GWKvUKFgnKSHuuCFrw", name: "ソ ナギ" },
    { id: "UC7hffDQLKIEG-_zoAQkMIvg", name: "明楽レイ" },
    { id: "UCClwIqTUn5LDpFucHyaAhHg", name: "イ ロハ" },
    { id: "UCCHH0nWYXFZmtDS_4tvMxHQ", name: "ヤン ナリ" },
    { id: "UClS6k3w1sPwlVFqK3-yID5A", name: "リュ ハリ" },
    { id: "UCnzZmBOSrQf2wDBbnsDajVw", name: "オ ジユ" },
    { id: "UCeGendL8CO5RkffB6IFwHow", name: "セフィナ" },
    { id: "UCrhhJPNsOqzNIkUfTABoSpg", name: "ハ ユン" },
    { id: "UCX88Pe54pxbJDSGIyGrzNdg", name: "ナ セラ" },

    { id: "UCpJtk0myFr5WnyfsmnInP-w", name: "ハナ マキア" },
    { id: "UC8Snw5i4eOJXEQqURAK17hQ", name: "ライ ガリレイ" },
    { id: "UCyRkQSuhJILuGOuXk10voPg", name: "ライラ アルストロエメリア" },
    { id: "UCjFu-9GHnabzSFRAYm1B9Dw", name: "エトナ クリムソン" },
    { id: "UCijNnZ-6m8g85UGaRAWuw7g", name: "ナギサ アルシニア" },
    { id: "UCMzVa7B8UEdrvUGsPmSgyjA", name: "デレム カド" },
];

// 2. タグ辞書（キーワードと除外ワード）
export const TAG_DICTIONARY: Record<string, { keywords: string[], exclude: string[] }> = {
    //動画の種類
    "歌ってみた": { keywords: ["歌ってみた", "Cover", "cover", "歌みた"], exclude: ["オリジナル曲", "Original Song", "MV", "歌枠", "カラオケ", "KARAOKE"] },
    "オリジナル曲": { keywords: ["オリジナル曲", "Original Song", "MV"], exclude: ["歌ってみた", "Cover", "cover", "歌みた", "歌枠", "カラオケ", "KARAOKE"] },
    "歌枠": { keywords: ["歌枠", "カラオケ", "KARAOKE"], exclude: ["歌ってみた", "Cover", "cover", "歌みた", "オリジナル曲", "Original Song", "MV"] },
    "雑談": { keywords: ["雑談", "Talk", "talk", "マシュマロ"], exclude: ["告知", "お知らせ"] },
    "3D": { keywords: ["3D"], exclude: ["3Dio", "にじ3D", "カービィ", "雑談", "振り返り", "ふりかえり"] },
    "告知": { keywords: ["告知", "発表"], exclude: [] },
    "ライブ": { keywords: ["ライブ", "LIVE", "Live"], exclude: ["雑談","ドライブ", "同時視聴", "Delivery", "Virtual to LIVE", "トライブ", "雑談", "振り返り", "ふりかえり"] },
    "同時視聴": { keywords: ["同時視聴"], exclude: [] },
    "凸待ち、逆凸": { keywords: ["凸"], exclude: [] },
    "ショート": { keywords: ["shorts"], exclude: [] },
    "切り抜き": { keywords: ["切り抜き"], exclude: [] },
    "Anniversary": { keywords: ["Anniversary", "ANNIVERSARY", "周年", "記念"], exclude: ["有馬記念"] },

    //全体長期企画
    "ストグラ": { keywords: ["ストグラ", "STGR", "stgr"], exclude: [] },

    //全体中期企画
    "VCRGTA": { keywords: ["VCRGTA","VCR GTA"], exclude: ["VCRGTA2", "VCRGTA3"] },
    "VCRGTA2": { keywords: ["VCRGTA2", "VCR GTA2","VCR GTA 2"], exclude: [] },
    "VCRGTA3": { keywords: ["VCRGTA3", "VCR GTA3","VCR GTA 3"], exclude: [] },
    "MADTOWN": { keywords: ["MADTOWN"], exclude: [] },
    "NEWTOWN": { keywords: ["NEWTOWN"], exclude: [] },
    "にじさんじGTA": { keywords: ["にじさんじGTA", "にじGTA"], exclude: [] },
    "VCRMincraft": { keywords: ["VCRMincraft", "VCR Mincraft"], exclude: [] },
    "VCRRUST": { keywords: ["VCRRUST", "VCR RUST",], exclude: [] },
    "VCRARK": { keywords: ["VCRGTA2", "VCR ARK",], exclude: [] },

    //大会、イベント
    "にじさんじフェス": { keywords: ["にじフェス"], exclude: [] },
    "V最協": { keywords: ["V最協", "V最"], exclude: [] },
    "KZHCUP": { keywords: ["KZHCUP", "KZH CUP"], exclude: [] },
    "LTK": { keywords: ["LTK"], exclude: [] },

    //個人長期企画
    "おはすず": { keywords: ["おはすず"], exclude: [] },
    "おはガク": { keywords: ["おはガク"], exclude: [] },
    "にゃるラジ": { keywords: ["にゃるラジ"], exclude: [] },

    //ゲームの種類
    "ARK": { keywords: ["ARK", "アーク"], exclude: ["ARC Raiders", "レイダー"] },
    "アークナイツ：エンドフィールド": { keywords: ["Endfield", "エンドフィールド"], exclude: [] },
    "ARC Raiders": { keywords: ["ARC Raiders"], exclude: [] },
    "IdentityV 第五人格": { keywords: ["IdentityV", "第五人格", "第5人格"], exclude: [] },
    "アイドルマスター": { keywords: ["アイドルマスター", "アイマス", "SideM", "シャニマス", "デレステ", "学マス"], exclude: [] },
    "OUTLAST": { keywords: ["OUTLAST", "アウトラスト"], exclude: [] },
    "青鬼": { keywords: ["青鬼"], exclude: [] },
    "おえかきの森": { keywords: ["おえかきの森", "おえ森"], exclude: [] },
    "Undertale": { keywords: ["Undertale", "アンダーテール", "アンテ"], exclude: [] },
    "Untitled Goose Game": { keywords: ["Untitled Goose Game", "ガチョウ"], exclude: [] },
    "Unpacking": { keywords: ["Unpacking", "アンパッキング"], exclude: [] },
    "一致するまで終われまテン": { keywords: ["一致するまで終われまテン"], exclude: [] },
    "It Takes Two": { keywords: ["It Takes Two"], exclude: [] },
    "イナズマイレブン": { keywords: ["イナズマイレブン", "イナイレ"], exclude: [] },
    "Ib": { keywords: ["Ib", "イヴ"], exclude: [] },
    "VALORANT": { keywords: ["VALORANT", "ヴァロラント", "ヴァロ"], exclude: [] },
    "Vampire Survivors": { keywords: ["Vampire Survivors", "ヴァンサバ"], exclude: [] },
    "UNO": { keywords: ["UNO"], exclude: [] },
    "ウマ娘": { keywords: ["ウマ娘"], exclude: [] },
    "エアホッケー": { keywords: ["エアホッケー"], exclude: [] },
    "Apex Legends": { keywords: ["Apex Legends", "エーペックス", "エペ", "えぺ"], exclude: [] },
    "Escape from Tarkov": { keywords: ["Escape from Tarkov", "タルコフ", "EFT"], exclude: [] },
    "エルデンリング": { keywords: ["エルデンリング", "ELDEN RING"], exclude: [] },
    "オーバーウォッチ": { keywords: ["オーバーウォッチ", "Overwatch", "OW"], exclude: [] },
    "Overcooked": { keywords: ["Overcooked", "オーバークック"], exclude: [] },
    "お絵かき心理テスト": { keywords: ["お絵かき心理テスト"], exclude: [] },
    "〇〇シミュレーター": { keywords: ["シミュレーター", "Simulator", "シミュレーション", "Simulation"], exclude: [] },
    "Only Up!": { keywords: ["Only Up", "オンリーアップ"], exclude: [] },
    "Gartic Phone": { keywords: ["Gartic Phone", "ガーティックフォン"], exclude: [] },
    "カイロソフト": { keywords: ["カイロソフト", "ゲーム発展", "海賊クエスト", "冒険キングダム", "冒険ダンジョン村", "こだわりラーメン", "箱庭タウンズ", "魔王城ものがたり", "ゆけむり温泉郷", "パティシエ部", "お住まい夢物語", "喫茶ブレンド", "すし街道", "開拓サバイバル島", "平安京ものがたり", "サッカークラブ物語", "まんが一本道", "どら焼き屋さん", "牧場ステークス", "名門ポケット学院"], exclude: [] },
    "塊魂": { keywords: ["塊魂", "カタマ魂"], exclude: [] },
    "漢字でGO!": { keywords: ["漢字でGO"], exclude: [] },
    "GUNDAM EVOLUTION": { keywords: ["GUNDAM EVOLUTION", "ガンエボ"], exclude: [] },
    "逆転裁判": { keywords: ["逆転裁判", "大逆転裁判"], exclude: [] },
    "Gang Beasts": { keywords: ["Gang Beasts", "ギャングビースト"], exclude: [] },
    "キングダムハーツ": { keywords: ["キングダムハーツ", "Kingdom Hearts", "KH3"], exclude: [] },
    "空気読み。": { keywords: ["空気読み"], exclude: [] },
    "Grand Theft Auto V": { keywords: ["Grand Theft Auto V","グラセフ"], exclude: [] },
    "プーさんのホームランダービー": { keywords: ["プーさんのホームランダービー", "ハチミツ泥棒"], exclude: [] },
    "Getting Over It": { keywords: ["Getting Over It", "壺おじ"], exclude: [] },
    "Get To Work": { keywords: ["Get To Work"], exclude: [] },
    "原神": { keywords: ["原神", "Genshin Impact"], exclude: [] },
    "Call of Duty": { keywords: ["Call of Duty", "CoD", "Modern Warfare"], exclude: [] },
    "ゴッドフィールド": { keywords: ["ゴッドフィールド", "God Field", "ゴッフィ"], exclude: [] },
    "ゴブリン・ノーム・ホーン": { keywords: ["ゴブリン・ノーム・ホーン"], exclude: [] },
    "Content Warning": { keywords: ["Content Warning"], exclude: [] },
    "SILENT HILL": { keywords: ["SILENT HILL", "サイレントヒル"], exclude: [] },
    "GeoGuessr": { keywords: ["GeoGuessr", "ジオゲッサー"], exclude: [] },
    "Civilization": { keywords: ["Civilization", "シヴィライゼーション", "Civ6", "Civ5"], exclude: [] },
    "シャドーコリドー": { keywords: ["Shadow Corridor", "影廊", "シャドーコリドー"], exclude: [] },
    "Shadowverse": { keywords: ["Shadowverse", "シャドウバース", "シャドバ"], exclude: [] },
    "雀魂": { keywords: ["雀魂", "じゃんたま", "にじさんじ麻雀杯"], exclude: [] },
    "Jump King": { keywords: ["Jump King", "ジャンプキング"], exclude: [] },
    "人生ゲーム": { keywords: ["人生ゲーム"], exclude: [] },
    "Super Bunny Man": { keywords: ["Super Bunny Man", "スーパーバニーマン"], exclude: [] },
    "スイカゲーム": { keywords: ["スイカゲーム"], exclude: [] },
    "すぎるRPG": { keywords: ["すぎるRPG","すぎたRPG"], exclude: [] },
    "Stardew Valley": { keywords: ["Stardew Valley", "スタデューバレー", "スタバ"], exclude: [] },
    "ストリートファイター": { keywords: ["ストリートファイター", "Street Fighter", "スト6", "SF6"], exclude: [] },
    "スプラトゥーン": { keywords: ["スプラトゥーン", "Splatoon", "スプラ"], exclude: [] },
    "Slither.io": { keywords: ["Slither.io", "スリザリオ"], exclude: [] },
    "世界のアソビ大全51": { keywords: ["アソビ大全"], exclude: [] },
    "SEKIRO": { keywords: ["SEKIRO", "隻狼"], exclude: [] },
    "ゼノブレイド": { keywords: ["ゼノブレイド", "Xenoblade"], exclude: [] },
    "7 Days to Die": { keywords: ["7 Days to Die", "7DTD"], exclude: [] },
    "ゼルダの伝説": { keywords: ["ゼルダの伝説", "Zelda", "ティアキン", "ブレワイ"], exclude: [] },
    "全国一般人常識チェック": { keywords: ["全国一般人常識チェック"], exclude: [] },
    "ゼンレスゾーンゼロ": { keywords: ["ゼンレスゾーンゼロ", "ゼンゼロ", "ZZZ"], exclude: [] },
    "ソニック": { keywords: ["ソニック・ザ・ヘッジホッグ", "Sonic"], exclude: [] },
    "Dark and Darker": { keywords: ["Dark and Darker", "DnD", "ダカダ"], exclude: [] },
    "ダークソウル": { keywords: ["DARK SOULS", "ダークソウル", "ダクソ"], exclude: [] },
    "大乱闘スマッシュブラザーズ": { keywords: ["大乱闘スマッシュブラザーズ", "スマブラ", "SSBU"], exclude: [] },
    "たまごっち": { keywords: ["たまごっち"], exclude: [] },
    "ダレカレ": { keywords: ["ダレカレ"], exclude: [] },
    "ダンガンロンパ": { keywords: ["ダンガンロンパ"], exclude: [] },
    "Chained Together": { keywords: ["Chained Together", "チェンパ"], exclude: [] },
    "違う冬のぼくら": { keywords: ["違う冬のぼくら", "BOKURA"], exclude: [] },
    "Chilla's Art": { keywords: ["Chilla's Art", "チラズアート", "ウミガリ", "夜勤事件", "地獄銭湯", "パラソーシャル", "夜間警備", "閉店事件", "新幹線０号", "呪われたデジカメ", "誘拐事件", "ヒトカラ", "赤マント", "事故物件", "行方不明", "例外配達", "終焉介護", "自撮", "犬鳴トンネル", "幽霊列車", "花子さん", "雪女"], exclude: ["監視", "カラオケ"] },
    "つぐのひ": { keywords: ["つぐのひ"], exclude: [] },
    "テイルズオブ": { keywords: ["テイルズオブ", "テイルズ オブ", "アライズ", "ベルセリア"], exclude: [] },
    "Dead by Daylight": { keywords: ["Dead by Daylight", "DbD", "デドバ"], exclude: [] },
    "Detroit: Become Human": { keywords: ["Detroit: Become Human", "デトロイト"], exclude: [] },
    "デュエル・マスターズ": { keywords: ["デュエル・マスターズ", "デュエマ", "デュエプレ"], exclude: [] },
    "Terraria": { keywords: ["Terraria", "テラリア"], exclude: [] },
    "天穂のサクナヒメ": { keywords: ["天穂のサクナヒメ", "サクナヒメ"], exclude: [] },
    "どうぶつの森": { keywords: ["どうぶつの森", "あつ森", "とび森"], exclude: [] },
    "東方Project": { keywords: ["東方Project", "東方紅魔郷", "東方"], exclude: [] },
    "ドーナツの穴": { keywords: ["ドーナツの穴", "Donut County"], exclude: [] },
    "ドキドキAI尋問ゲーム": { keywords: ["ドキドキAI尋問ゲーム"], exclude: [] },
    "ドキドキ文芸部！": { keywords: ["ドキドキ文芸部", "DDLC"], exclude: [] },
    "ときめきメモリアル": { keywords: ["ときめきメモリアル", "ときメモ"], exclude: [] },
    "都市伝説解体センター": { keywords: ["都市伝説解体センター"], exclude: [] },
    "ドラゴンクエスト": { keywords: ["ドラゴンクエスト", "ドラクエ", "DQ"], exclude: [] },
    "ドラゴンボールZ KAKAROT": { keywords: ["ドラゴンボールZ KAKAROT", "カカロット"], exclude: [] },
    "Trombone Champ": { keywords: ["Trombone Champ", "トロンボーン"], exclude: [] },
    "ドンキーコング": { keywords: ["ドンキーコング"], exclude: [] },
    "DON'T SCREAM": { keywords: ["DON'T SCREAM", "叫んではいけない"], exclude: [] },
    "NieRシリーズ": { keywords: ["NieR", "ニーア オートマタ", "ニーア レプリカント", "NieR:Automata", "NieR Replicant"], exclude: [] },
    "NEEDY GIRL OVERDOSE": { keywords: ["NEEDY GIRL OVERDOSE", "超てんちゃん"], exclude: [] },
    "にじさんじ共通テスト": { keywords: ["にじさんじ共通テスト"], exclude: [] },
    "にじさんじのタイプ診断": { keywords: ["にじさんじのタイプ診断"], exclude: [] },
    "日本事故物件監視協会": { keywords: ["日本事故物件監視協会", "JSO"], exclude: [] },
    "Nintendo Switch Sports": { keywords: ["Nintendo Switch Sports", "スイッチスポーツ"], exclude: [] },
    "No, I'm not a Human": { keywords: ["No, I'm not a Human"], exclude: [] },
    "脳を鍛える大人のトレーニング": { keywords: ["脳を鍛える大人のトレーニング", "脳トレ"], exclude: [] },
    "Party Animals": { keywords: ["Party Animals"], exclude: [] },
    "バイオハザード": { keywords: ["バイオハザード", "Resident Evil", "RE:2", "RE:3", "RE:4", "ヴィレッジ"], exclude: [] },
    "Pineapple on pizza": { keywords: ["Pineapple on pizza", "パイナップルオンピザ"], exclude: [] },
    "パスパルトゥー": { keywords: ["Passpartout", "パスパルトゥー"], exclude: [] },
    "1/8192": { keywords: ["1/8192"], exclude: [] },
    "8番出口": { keywords: ["8番出口"], exclude: [] },
    "8番のりば": { keywords: ["8番のりば"], exclude: [] },
    "Buckshot Roulette": { keywords: ["Buckshot Roulette", "バックショットルーレット"], exclude: [] },
    "パドルパドルパドる": { keywords: ["パドルパドルパドる"], exclude: [] },
    "パワプロ": { keywords: ["パワプロ", "実況パワフルプロ野球", "栄冠ナイン", "にじさんじ甲子園"], exclude: [] },
    "PEAK": { keywords: ["PEAK"], exclude: [] },
    "PUBG": { keywords: ["PUBG"], exclude: [] },
    "ピクミン": { keywords: ["ピクミン", "Pikmin"], exclude: [] },
    "PICO PARK": { keywords: ["PICO PARK"], exclude: [] },
    "Human Fall Flat": { keywords: ["Human Fall Flat", "ヒューマンフォールフラット"], exclude: [] },
    "ファイアーエムブレム": { keywords: ["ファイアーエムブレム", "Fire Emblem", "FEエンゲージ", "FE風花雪月"], exclude: [] },
    "ファイナルファンタジー": { keywords: ["ファイナルファンタジー", "FINAL FANTASY", " FF7 ", " FF10 ", " FF14 ", " FF16 ", "FF"], exclude: ["COFFEE"] },
    "Phasmophobia": { keywords: ["Phasmophobia", "ファズモフォビア", "ファズモ"], exclude: [] },
    "ファミレスを享受せよ": { keywords: ["ファミレスを享受せよ"], exclude: [] },
    "FIFA": { keywords: ["FIFA"], exclude: [] },
    "Fate/Grand Order": { keywords: ["Fate/Grand Order", " FGO "], exclude: [] },
    "Fall Guys": { keywords: ["Fall Guys", "フォールガイズ"], exclude: [] },
    "不思議のダンジョン": { keywords: ["風来のシレン", "トルネコの大冒険", "不思議のダンジョン"], exclude: [] },
    "ぷよテト": { keywords: ["ぷよテト", "ぷよぷよ", "テトリス"], exclude: [] },
    "ブラッドボーン": { keywords: ["Bloodborne", "ブラッドボーン"], exclude: [] },
    "ブルーアーカイブ": { keywords: ["ブルーアーカイブ", "ブルアカ"], exclude: [] },
    "Project Winter": { keywords: ["Project Winter", "雪山人狼"], exclude: [] },
    "プロジェクトセカイ": { keywords: ["プロジェクトセカイ", "プロセカ"], exclude: [] },
    "ペルソナ": { keywords: ["ペルソナ3", "ペルソナ4", "ペルソナ5", "PERSONA"], exclude: [] },
    "ポーカーチェイス": { keywords: ["ポーカーチェイス", "ポカチェ"], exclude: [] },
    "Portal": { keywords: ["Portal", "ポータル"], exclude: [] },
    "崩壊": { keywords: ["崩壊3rd", "崩壊：スターレイル", "スタレ"], exclude: [] },
    "牧場物語": { keywords: ["牧場物語"], exclude: [] },
    "ぼくのなつやすみ": { keywords: ["ぼくのなつやすみ", "ぼくなつ"], exclude: [] },
    "Hogwarts Legacy": { keywords: ["Hogwarts Legacy", "ホグワーツ・レガシー", "ホグワーツレガシー"], exclude: [] },
    "ポケットモンスター": { keywords: ["ポケットモンスター", "ポケモン", "Pokemon", "ポケモンSV", "剣盾", "ダイパ"], exclude: [] },
    "星のカービィ": { keywords: ["星のカービィ", "Kirby"], exclude: [] },
    "Poppy Playtime": { keywords: ["Poppy Playtime", "ポピープレイタイム"], exclude: [] },
    "ボンバーマン": { keywords: ["ボンバーマン", "BOMBERMAN"], exclude: [] },
    "Marvel Rivals": { keywords: ["Marvel Rivals", "マーベル・ライバルズ"], exclude: [] },
    "Minecraft": { keywords: ["Minecraft", "マイクラ", "マインクラフト"], exclude: [] },
    "魔界村": { keywords: ["魔界村", "Ghosts 'n Goblins"], exclude: [] },
    "MOTHER": { keywords: ["MOTHER", "MOTHER2", "MOTHER3"], exclude: [] },
    "魔女の家": { keywords: ["魔女の家"], exclude: [] },
    "魔法少女ノ魔女裁判": { keywords: ["魔法少女ノ魔女裁判"], exclude: [] },
    "マリオカート8DX": { keywords: ["マリオカート8", "マリカ8DX", "MK8DX"], exclude: [] },
    "マリオカート": { keywords: ["マリオカート", "マリカ", "MK8", "にじさんじ杯"], exclude: [] },
    "マリオシリーズ": { keywords: ["スーパーマリオ", "マリオブラザーズ", "マリオワンダー", "マリオメーカー"], exclude: ["マリオカート", "マリオパーティ"] },
    "マリオパーティ": { keywords: ["マリオパーティ", "マリパ"], exclude: [] },
    "Miitopia": { keywords: ["Miitopia", "ミートピア"], exclude: [] },
    "MIMESIS": { keywords: ["MIMESIS", "ミメシス"], exclude: [] },
    "鳴潮": { keywords: ["鳴潮", "Wuthering Waves"], exclude: [] },
    "メイプルストーリー": { keywords: ["メイプルストーリー"], exclude: [] },
    "メタルギア": { keywords: ["メタルギア", "METAL GEAR", "MGS"], exclude: [] },
    "メトロイド": { keywords: ["メトロイド", "METROID"], exclude: [] },
    "桃太郎電鉄": { keywords: ["桃太郎電鉄", "桃鉄"], exclude: [] },
    "モンスターハンター": { keywords: ["モンスターハンター", "モンハン", "Monster Hunter", "MHW", "MHR"], exclude: [] },
    "やわらかあたま塾": { keywords: ["やわらかあたま塾", "Big Brain Academy"], exclude: [] },
    "遊戯王": { keywords: ["遊戯王", "Yu-Gi-Oh", "マスターデュエル", "Master Duel"], exclude: [] },
    "夜廻": { keywords: ["夜廻", "深夜廻"], exclude: [] },
    "Rust": { keywords: ["Rust", "ラスト", "VCR Rust", "にじ鯖Rust"], exclude: [] },
    "Raft": { keywords: ["Raft", "ラフト"], exclude: [] },
    "League of Legends": { keywords: ["League of Legends", "LoL", "リーグ・オブ・レジェンド"], exclude: [] },
    "Lethal Company": { keywords: ["Lethal Company", "リーサルカンパニー"], exclude: [] },
    "リズム天国": { keywords: ["リズム天国"], exclude: [] },
    "LITTLE NIGHTMARES": { keywords: ["LITTLE NIGHTMARES", "リトルナイトメア"], exclude: [] },
    "龍が如く": { keywords: ["龍が如く", "Yakuza", "Like a Dragon", "ジャッジアイズ"], exclude: [] },
    "利用規約に同意したい": { keywords: ["利用規約に同意したい"], exclude: [] },
    "リングフィット": { keywords: ["リングフィット", "Ring Fit Adventure"], exclude: [] },
    "R.E.P.O.": { keywords: ["R.E.P.O."], exclude: [] },
    "ロックマン": { keywords: ["ロックマン", "Mega Man", "エグゼ"], exclude: [] },
    "ワリオ": { keywords: ["ワリオ", "メイド イン ワリオ", "WarioWare"], exclude: [] },
    "1-2-Switch": { keywords: ["1-2-Switch", "ワンツースイッチ"], exclude: [] }


};

/**
 * タイトルからカテゴリを判定する共通関数
 */
// lib/constants.ts

export function judgeCategory(title: string): string[] {
    const categories: string[] = [];

    // TAG_DICTIONARY が定義されている前提
    for (const [category, rule] of Object.entries(TAG_DICTIONARY)) {
        const hasKeyword = rule.keywords.some(k =>
            title.toLowerCase().includes(k.toLowerCase())
        );
        const hasExclude = rule.exclude.some(e =>
            title.toLowerCase().includes(e.toLowerCase())
        );

        if (hasKeyword && !hasExclude) {
            categories.push(category);
        }
    }

    // ここが重要！必ず配列形式で返します
    return categories.length > 0 ? categories : ["その他"];
}